### ISSUE TITLE
VIRUS DETECTED!

### ISSUE THREAD

**Issue by wisdomtooth** [kopurando/virga.app-youtube-dl-GUI-for-OS-X#8]
Avast detected and quantined this app as a virus when I tried running it. Irk!

**Comment by kopurando** [comment]
hm, does Avast say anything meaningful about his actions? Defo a false positive, I just hope Avast is better at catching real viruses.

**Comment by wisdomtooth** [comment]
This:

![vcombined](https://user-images.githubusercontent.com/523901/42879669-c7b2de62-8ad4-11e8-8ffd-e6be7ebb08ed.png)

**Comment by wisdomtooth** [comment]
So you closed the issue without even looking into it?

Yep, uninstalled. Thanks.

**Comment by kopurando** [comment]
According to screenshots, infection was triggered not by virga app, but by some of your chrome extensions. As I understand, it replaces links in pages you visit with some malware-ish stuff. Please review extensions you have installed in Chrome and permissions you give to them.

**Comment by kopurando** [comment]
Seek more help here:
https://www.google.com.sg/search?q=spigot-x+crx&oq=spigot-x+crx

Spigot can be notoriously hard to eradicate, esp. if you have several browsers in your system.

One of the most known malware agents are uTorrent and various video downloading apps, which is why I wrote virga to begin with -- to replace all that malware infested downloaders with an open-source tool. Hope it helps.
